### ISSUE TITLE
Add phpMyAdmin to docker-compose.yml file

### ISSUE THREAD

**Issue by timrsfo** [andreaskoch/dockerized-magento#18]
This is more of a heads-up than an issue, if you add the following to the end of the docker-compose.yml file users will have browser access to the db

```
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   links:
    - mysql:mysql
   ports:
     - 9191:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: pw
     PMA_HOST: mysql
```

NOTE: 9191 is the host port  http://localhost:9191 - will bring up phyMyAdmin

BTW: Thanks for dockerized-magento, its great for creating a test/learning environment!
