### ISSUE TITLE
Cannot start, getting this error:

### ISSUE THREAD

**Issue by juslintek** [andreaskoch/dockerized-magento#39]
```
ERROR: for nginx  Cannot start service nginx: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/d/www/zaidimustalai.lt/dockerized-magento/config/nginx/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/78cbfc83bd466ad2b40f190912576a8a2299a57d091caf4767c61097a304d8a7\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/78cbfc83bd466ad2b40f190912576a8a2299a57d091caf4767c61097a304d8a7/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

My docker-compose.yml as well I'm using Windows 10 Home Edition:
```
installer:
  image: andreaskoch/dockerized-magento-installer
  environment:
    DOMAIN: dockerized-magento.local
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  volumes_from:
    - nginx
  volumes:
    - ./config/installer/php/php.ini:/usr/local/etc/php/php.ini
    - ./config/installer/magerun/n98-magerun.yaml.tmpl:/etc/n98-magerun.yaml.tmpl
    - ./config/installer/magento/local.xml.tmpl:/etc/local.xml.tmpl
    - ./config/installer/magento/fpc.xml.tmpl:/etc/fpc.xml.tmpl
    - ./config/installer/bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    - ./config/installer/bin/install.sh:/bin/install.sh
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "elasticsearch:elasticsearch"
    - "mysql:mysql"
  entrypoint: /bin/install.sh

nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/nginx/includes:/etc/nginx/includes
    - ./config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  image: andreaskoch/dockerized-magento-php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "elasticsearch:elasticsearch"
    - "mysql:mysql"
  volumes:
    - .:/var/www/html
mysql:
  image: mariadb:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
  volumes:
    - ./data/mariadb:/var/lib/mariadb
elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
cache:
  image: redis:latest
fullpagecache:
  image: redis:latest
sessions:
  image: redis:latest
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_PORT: 3306
```
